# Generated by Django 5.0.6 on 2024-07-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_command_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(null=True, upload_to='product/'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('products', models.ManyToManyField(related_name='categories', to='orders.product')),
            ],
        ),
    ]
